In [4]:
import os
os.getcwd()

'C:\\Users\\qian\\python基础\\code'

#### 0、 numpy数组对象

In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,10,4])
a1

array([ 1,  2, 10,  4])

In [4]:
a2=np.array([[1,2,3,4],[4,15,6,17]])
a2

array([[ 1,  2,  3,  4],
       [ 4, 15,  6, 17]])

In [5]:
a2.size

8

In [6]:
a2.shape

(2, 4)

In [7]:
a2.ndim

2

In [8]:
a2.dtype

dtype('int32')

In [9]:
np.float(50)

50.0

In [10]:
np.int(50.35)

50

In [11]:
hot=np.dtype([('name',np.str_,10),('number',np.int64),('price',np.float64)])
hot

dtype([('name', '<U10'), ('number', '<i8'), ('price', '<f8')])

In [12]:
hotbuy=np.array([('一锅两头牛美味双人餐','35','98'),('小龙腾四海100元代金券','43','79'),('酸汤鱼火锅2-3人餐','1','165')])
hotbuy

array([['一锅两头牛美味双人餐', '35', '98'],
       ['小龙腾四海100元代金券', '43', '79'],
       ['酸汤鱼火锅2-3人餐', '1', '165']], dtype='<U12')

#### 1、数据读入

In [5]:
import numpy as np
hot=np.dtype([('团购活动ID',np.str_,10),('团购名',np.str_,10),('店名',np.str_,10),('购买人数',np.float64),('团购价',np.str_,10),('市场价',np.str_,10),('地址',np.str_,10)])

In [6]:
raw_data = np.loadtxt('coupon_nm_new.csv',delimiter=",",dtype=hot)

In [31]:
raw_data 

array([('38744470', '壹分之贰豪华生日派对', '壹分之贰聚会吧桌游轰',  0., '0', '0', '【西安市雁塔区小寨东'),
       ('38632123', '壹分之贰豪华棋牌包间', '壹分之贰聚会吧桌游轰',  0., '0', '0', '【西安市雁塔区小寨东'),
       ('38744514', '壹分之贰豪华生日派对', '壹分之贰聚会吧桌游轰',  0., '0', '0', '【西安市雁塔区小寨东'),
       ...,
       ('30029899', '骨得香大盆骨炒鸡4到', '骨得香大盆骨',  4., '0', '0', '【郑州市巩义市货场路'),
       ('30029206', '炒鸡双人餐！免费停车', '骨得香大盆骨', 27., '0', '0', '【郑州市巩义市货场路'),
       ('38716258', '骨得香烧烤100元代', '骨得香大盆骨',  0., '0', '0', '【郑州市巩义市货场路')],
      dtype=[('团购活动ID', '<U10'), ('团购名', '<U10'), ('店名', '<U10'), ('购买人数', '<f8'), ('团购价', '<U10'), ('市场价', '<U10'), ('地址', '<U10')])

In [32]:
shop=raw_data[['店名']]

In [33]:
shop.shape

(1855,)

#### 2、数据去重

In [34]:
(np.unique(shop)).shape

(628,)

#### 3、基本索引方式

In [35]:
#索引第3家店铺
shop[2]

('壹分之贰聚会吧桌游轰',)

In [36]:
#索引第3家到第5家店铺
shop[2:6]

array([('壹分之贰聚会吧桌游轰',), ('壹分之贰聚会吧桌游轰',), ('六婆串串香火锅',), ('1+N生日求婚聚会P',)],
      dtype=[('店名', '<U10')])

In [37]:
#建立三维数组arr
arr=np.array([raw_data['团购活动ID'],raw_data['团购名'],raw_data['购买人数']])
arr

array([['38744470', '38632123', '38744514', ..., '30029899', '30029206',
        '38716258'],
       ['壹分之贰豪华生日派对', '壹分之贰豪华棋牌包间', '壹分之贰豪华生日派对', ..., '骨得香大盆骨炒鸡4到',
        '炒鸡双人餐！免费停车', '骨得香烧烤100元代'],
       ['0.0', '0.0', '0.0', ..., '4.0', '27.0', '0.0']], dtype='<U32')

In [38]:
#数组转置
arrt=arr.T
arrt

array([['38744470', '壹分之贰豪华生日派对', '0.0'],
       ['38632123', '壹分之贰豪华棋牌包间', '0.0'],
       ['38744514', '壹分之贰豪华生日派对', '0.0'],
       ...,
       ['30029899', '骨得香大盆骨炒鸡4到', '4.0'],
       ['30029206', '炒鸡双人餐！免费停车', '27.0'],
       ['38716258', '骨得香烧烤100元代', '0.0']], dtype='<U32')

In [39]:
#数组索引
arrt[0,0:3]

array(['38744470', '壹分之贰豪华生日派对', '0.0'], dtype='<U32')

In [41]:
raw_data[raw_data['购买人数']==50]

array([('39113898', '大宅门2-3人套餐', '大宅门火锅(西关正街', 50., '118', '266', '【西安市阎良区延安街'),
       ('36710627', '经典4人餐！免费Wi', '槿熙芝士年糕自助火锅', 50., '0', '0', '【西安市碑林区东大街'),
       ('30752267', '辣巴人50元代金券', '辣巴人', 50., '39.9', '50', '【西安市碑林区体育场'),
       ('38572198', '川香石锅鱼3-4人餐', '李双全川香石锅鱼', 50., '126', '178', '【郑州市新郑市薛店镇'),
       ('5870273', '王婆大虾100元代金', '王婆大虾(华信店)', 50., '88', '100', '【郑州市管城区中州大')],
      dtype=[('团购活动ID', '<U10'), ('团购名', '<U10'), ('店名', '<U10'), ('购买人数', '<f8'), ('团购价', '<U10'), ('市场价', '<U10'), ('地址', '<U10')])

#### 4、统计分析

In [46]:
price=raw_data['团购价']
price

array(['0', '0', '0', ..., '998', '998', '998'], dtype='<U10')

In [51]:
price.dtype

dtype('<U10')

In [60]:
price = price.astype(float)   # 字符串转为浮点型
print (price.dtype)
print (price)

float64
[  0.   0.   0. ... 998. 998. 998.]


In [61]:
price.sort()
print('排序后团购价为:',price)

排序后团购价为: [   0.    0.    0. ... 1588. 1688. 3999.]


In [62]:
np.sum(price)

226989.87000000002

In [55]:
np.std(price)

155.61011643601802

In [56]:
np.mean(price)

122.36650673854447

In [57]:
np.var(price)

24214.508337231087

In [58]:
np.max(price)

3999.0

In [59]:
np.min(price)

0.0

#### 5、生成随机数

In [207]:
#生成随机数
np.random.random(20)

array([0.63534754, 0.68912726, 0.32301646, 0.14234035, 0.72829197,
       0.76743477, 0.02250209, 0.72653032, 0.29544261, 0.53718881,
       0.09598504, 0.22434429, 0.90711073, 0.20033604, 0.15982962,
       0.55679766, 0.04257718, 0.07168316, 0.60999567, 0.33211491])

In [213]:
#生成均匀分布
np.random.rand(8,4)

array([[0.90202134, 0.29979331, 0.13252858, 0.05392595],
       [0.38065824, 0.92193558, 0.06532746, 0.62848311],
       [0.77102953, 0.95565239, 0.89153967, 0.04918805],
       [0.01272094, 0.21873301, 0.77375241, 0.49076084],
       [0.099932  , 0.25264892, 0.32953474, 0.98330953],
       [0.89752724, 0.5237449 , 0.97205729, 0.361902  ],
       [0.6083955 , 0.36952581, 0.96361376, 0.88695011],
       [0.17634999, 0.2360799 , 0.85701326, 0.80252552]])

In [214]:
#生成服从正态分布的随机数
np.random.randn(8,4)

array([[ 1.06662952e+00, -1.10334227e+00,  2.46766934e-01,
        -9.13099128e-01],
       [-1.66661561e+00, -2.48622850e-01, -1.16312318e+00,
         1.67684933e-01],
       [-5.38906943e-01, -1.87720914e-03,  3.15490953e-01,
        -3.72297328e-02],
       [-2.13044086e+00, -3.25575916e-02, -5.69309498e-01,
        -9.66048618e-01],
       [-8.54760574e-01,  2.32424895e-01, -1.83194342e+00,
         3.31637570e-01],
       [-1.83256774e-01,  1.43539529e+00, -8.00379430e-01,
        -1.85473778e+00],
       [-1.47028309e+00, -1.40293303e+00,  6.37901830e-01,
         6.02960143e-01],
       [ 7.07428371e-01, -7.13739293e-01, -4.99568280e-01,
         4.13974160e-01]])

In [215]:
#生成给定上下限范围的随机数
np.random.randint(3,5,size=[3,5])

array([[3, 3, 4, 3, 3],
       [4, 4, 3, 3, 4],
       [3, 4, 3, 3, 3]])